[terminal.shell]
program = "C:\\Program Files\\WSL\\wsl.exe"
args = ["--cd ~"]

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

[font]
normal = { family = "LiterationMono Nerd Font Mono", style = "Regular"}
size = 13

[window]
dynamic_title = false

[cursor]
style = { shape= "Block", blinking = "Never" }
vi_mode_style = { shape = "Beam", blinking = "Always" }
unfocused_hollow = false

# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors.primary]

# background = "#282a36"
foreground = "#f8f8f2"
bright_foreground = "#ffffff"

# foreground = "#c0c0c0"
background = "#1d1f21"


[colors.cursor]

text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#44475a"

[colors.normal]

black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]

black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.search.matches]

foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]

foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]

background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]

foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]

foreground = "#f1fa8c"
background = "#282a36"
